modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="oskarspeemod"
version="BD1  / A0.1"
displayName="Oskar's Pee Mod"
credits="Oskar"
displayURL="https://mcreator.net"
authors="OskarQwert / Oskar"
description='''
Adds PEE (yes pee) to minecraft
'''

[[dependencies.oskarspeemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




